### ISSUE TITLE
Configuração para Login da aplicação

### ISSUE THREAD

**Issue by rdiegoss** [portalsuperacao/superacao-app#11]
Boa tarde galera,

Atualizei o projeto aqui e já iria pegar um card no trello, porém, ao tentar logar tive que fazer muita "gambiarra" para entrar.... 

Teria algum jeito prático para logar na aplicação? Já criei conta no firebase, coloquei a configuração nos "Enviromments" porém só com isso, se eu for me cadastrar só aparece uma mensagem "Houve um erro, ...." 

Como nunca mexi com firebase, queria saber se teria alguma configuração que eu faça lá no console do firebase ou na apliacação para "passar" desse "erro.

Abraço.

**Comment by abmxer** [comment]
Fala Rodrigo! 

Vou criar um Issue pra tratar melhor este erro. Não sei o motivo dele. 

Eu só fiz o login via Facebook e ele tá ok. Não testei ainda via cadastro direto, o @diegodsgarcia  pode ajudar nisso e também ver como melhorar a documentação se for o caso.

Valeu!

**Comment by rdiegoss** [comment]
Tudo bem, vou tentar pelo facebook.

**Comment by rdiegoss** [comment]
@abmxer Tentei pelo Facebook, porém vi que ele pega os dados e tenta jogar no Firebase, que acaba indo para o mesmo problema.

Vou aguardar o @diegodsgarcia me dizer qual a melhor forma de configurar, pois mesmo tendo criado o projeto no firebase e colocando nos enviromments as credenciais, ainda esta dano esse mesmo problema.

Abraços.

**Comment by diegodsgarcia** [comment]
@rdiegoss Você pode mostrar o error que seu console gera no seu navegador?

**Comment by rdiegoss** [comment]
@diegodsgarcia Consegui resolver aqui, bastava habilitar o OAuth no Firebase, eu como leigo ainda nessa parte, fui mexendo e vi isso, quando ativei lá, consegui logar normalmente.

Mas desde já, obrigado.
