### ISSUE TITLE
Invites do trello e slack...

### ISSUE THREAD

**Issue by rdiegoss** [portalsuperacao/superacao-app#3]
E ai, tudo bem? 

Participamos de uma reunião sobre o App, porém falta adicionar a quem participou da reunião os cards no trello e o invite para o slack.

Meu email: rdiegoss@gmail.com

**Comment by diegodsgarcia** [comment]
Convite enviado! Caso alguem precisa de mais convite,vou deixa essa Issue aberta por uns dias

**Comment by rdiegoss** [comment]
Slack deu certo, porém trello ainda não recebi.

**Comment by rmdevelopers** [comment]
Pessoal, recebi nada. Meu e-mail:
rafaelmp.web@gmail.com

**Comment by abmxer** [comment]
Fala Rafael! Te add agora ao slack! Me fala teu user do Trello tb!

**Comment by rdiegoss** [comment]
@abmxer Se poder me add no trello também, meu email é rdiegoss@gmail.com.

**Comment by rmdevelopers** [comment]
Meu trello: rafaelmariano1
