### ISSUE TITLE
Problema ao iniciar projeto

### ISSUE THREAD

**Issue by rdiegoss** [portalsuperacao/superacao-app#4]
Olá galera!!

Alguém mais teve problema ao iniciar pelo docker ? (Já rodei o docker-composer build)

![screen shot 2017-03-28 at 20 46 19](https://cloud.githubusercontent.com/assets/10976074/24432328/c602e35a-13f7-11e7-92f3-58a65eaec657.png)

Tentei iniciar via "Ionic serve" normal e também deu esse erro:

![screen shot 2017-03-28 at 20 47 54](https://cloud.githubusercontent.com/assets/10976074/24432343/d8bb27d2-13f7-11e7-9ce5-5a440559855b.png)

Help me !

**Comment by diegodsgarcia** [comment]
Opa beleza cara? Então eu crie lá uma PR, com a possivel solução, o primeiro problema é facil de resolver, que é só a forma de importação do moment que foi atualizado, porem deu outro probleminha aqui incompatibilidade com o plugin do Rollup e as variáveis de ambiente. Confesso que esse consertei no chute, mas parece que rolou hahahhahaha. Me fala se deu certo ai
